import type { DiagramId, DiagramSpec, DiagramStep } from './diagram';

const raceBase: DiagramStep[] = [
  { caption: '두 요청이 거의 동시에 들어옵니다.', show: ['a', 'b'], active: ['a', 'b'] },
  { caption: '각자 다른 잠금을 잡아서 서로를 기다리지 않습니다.', show: ['a', 'b', 'lockA', 'lockB'], active: ['lockA', 'lockB'] },
  { caption: '둘 다 같은 행이 있는지 확인합니다. 아직 커밋 전이라 둘 다 없다고 봅니다.', show: ['a', 'b', 'lockA', 'lockB', 'check'], active: ['check'] },
  { caption: 'A가 먼저 행을 넣습니다.', show: ['a', 'b', 'lockA', 'lockB', 'check', 'row1'], active: ['row1'] },
];

export const DIAGRAMS: Record<DiagramId, DiagramSpec> = {
  'race-condition': {
    id: 'race-condition',
    title: '정산 원장 중복 삽입 과정',
    width: 360,
    height: 244,
    nodes: [
      { id: 'a', label: '서비스 A', x: 20, y: 12, w: 140, h: 32 },
      { id: 'b', label: '서비스 B', x: 200, y: 12, w: 140, h: 32 },
      { id: 'lockA', label: '잠금 A', x: 20, y: 60, w: 140, h: 28 },
      { id: 'lockB', label: '잠금 B', x: 200, y: 60, w: 140, h: 28 },
      { id: 'check', label: '같은 행 있나? 없음', x: 70, y: 106, w: 220, h: 28 },
      { id: 'row1', label: '같은 옵션, 같은 상태', x: 50, y: 152, w: 260, h: 30 },
      { id: 'row2', label: '같은 옵션, 같은 상태 (중복)', x: 50, y: 196, w: 260, h: 30 },
      { id: 'reject', label: '두 번째 INSERT 거절', x: 50, y: 196, w: 260, h: 30 },
    ],
    edges: [
      { from: 'a', to: 'lockA' },
      { from: 'b', to: 'lockB' },
      { from: 'lockA', to: 'check' },
      { from: 'lockB', to: 'check' },
      { from: 'check', to: 'row1' },
      { from: 'check', to: 'row2' },
      { from: 'check', to: 'reject' },
    ],
    steps: [
      ...raceBase,
      { caption: 'B도 행을 넣습니다. 같은 기록이 두 번 쌓였습니다.', show: ['a', 'b', 'lockA', 'lockB', 'check', 'row1', 'row2'], active: ['row2'], danger: ['row2'] },
    ],
    variant: {
      label: '원장 유니크 키 적용',
      steps: [
        ...raceBase,
        { caption: '원장의 유니크 키가 두 번째 INSERT를 거절합니다. 한 행만 남습니다.', show: ['a', 'b', 'lockA', 'lockB', 'check', 'row1', 'reject'], active: ['reject'] },
      ],
    },
  },
  'signal-pipeline': {
    id: 'signal-pipeline',
    title: '이상 신호를 찾아 문장으로 알리는 흐름',
    width: 360,
    height: 246,
    nodes: [
      { id: 'data', label: '주문, 회원 데이터', x: 100, y: 10, w: 160, h: 30 },
      { id: 'views', label: '핵심 지표 뷰 3개', x: 100, y: 58, w: 160, h: 30 },
      { id: 'detect', label: '이상 신호 탐지', x: 100, y: 106, w: 160, h: 30 },
      { id: 'code', label: '수치와 원인: 코드', x: 10, y: 156, w: 160, h: 30 },
      { id: 'llm', label: '문장: LLM', x: 190, y: 156, w: 160, h: 30 },
      { id: 'alert', label: '알림', x: 100, y: 206, w: 160, h: 30 },
    ],
    edges: [
      { from: 'data', to: 'views' },
      { from: 'views', to: 'detect' },
      { from: 'detect', to: 'code' },
      { from: 'detect', to: 'llm' },
      { from: 'code', to: 'alert' },
      { from: 'llm', to: 'alert' },
    ],
    steps: [
      { caption: '주문과 회원 데이터에서 시작합니다.', show: ['data'], active: ['data'] },
      { caption: '요구사항 12개를 핵심 지표 3개로 줄여 뷰로 만듭니다.', show: ['data', 'views'], active: ['views'] },
      { caption: '평소와 다른 움직임(이상 신호)을 찾습니다.', show: ['data', 'views', 'detect'], active: ['detect'] },
      { caption: '수치와 원인은 코드가 정하고, LLM은 문장만 다듬습니다.', show: ['data', 'views', 'detect', 'code', 'llm'], active: ['code', 'llm'] },
      { caption: '정리한 문장을 알림으로 보냅니다.', show: ['data', 'views', 'detect', 'code', 'llm', 'alert'], active: ['alert'] },
    ],
  },
  'privacy-flow': {
    id: 'privacy-flow',
    title: '개인정보 조회 경로 일원화',
    width: 360,
    height: 220,
    nodes: [
      { id: 'f1', label: '기능 1', x: 10, y: 20, w: 110, h: 28 },
      { id: 'f2', label: '기능 2', x: 10, y: 96, w: 110, h: 28 },
      { id: 'f3', label: '기능 3', x: 10, y: 172, w: 110, h: 28 },
      { id: 'api', label: '표준 조회 API', x: 140, y: 96, w: 100, h: 28 },
      { id: 's1', label: '시스템 1', x: 260, y: 20, w: 90, h: 28 },
      { id: 's2', label: '시스템 2', x: 260, y: 72, w: 90, h: 28 },
      { id: 's3', label: '시스템 3', x: 260, y: 124, w: 90, h: 28 },
      { id: 's4', label: '시스템 4', x: 260, y: 176, w: 90, h: 28 },
    ],
    edges: [
      { from: 'f1', to: 's1' },
      { from: 'f1', to: 's2' },
      { from: 'f2', to: 's2' },
      { from: 'f3', to: 's3' },
      { from: 'f3', to: 's4' },
      { from: 'f1', to: 'api' },
      { from: 'f2', to: 'api' },
      { from: 'f3', to: 'api' },
      { from: 'api', to: 's1' },
      { from: 'api', to: 's2' },
      { from: 'api', to: 's3' },
      { from: 'api', to: 's4' },
    ],
    steps: [
      {
        caption: '기능마다 회원 개인정보를 서로 다른 경로로 조회했습니다.',
        show: ['f1', 'f2', 'f3', 's1', 's2', 's3', 's4'],
        active: [],
        edges: [['f1', 's1'], ['f1', 's2'], ['f2', 's2'], ['f3', 's3'], ['f3', 's4']],
      },
      {
        caption: '조회 경로를 표준 API 하나로 모읍니다.',
        show: ['f1', 'f2', 'f3', 'api', 's1', 's2', 's3', 's4'],
        active: ['api'],
        edges: [['f1', 'api'], ['f2', 'api'], ['f3', 'api'], ['api', 's1'], ['api', 's2'], ['api', 's3'], ['api', 's4']],
      },
    ],
  },
  'alert-flow': {
    id: 'alert-flow',
    title: '알림 체계',
    width: 360,
    height: 250,
    nodes: [
      { id: 'src', label: '지표, 로그 수집', x: 100, y: 10, w: 160, h: 30 },
      { id: 'rules', label: '알림 규칙 36개', x: 100, y: 58, w: 160, h: 30 },
      { id: 's1', label: '긴급 19', x: 10, y: 110, w: 100, h: 30 },
      { id: 's2', label: '높음 4', x: 130, y: 110, w: 100, h: 30 },
      { id: 's3', label: '통지 13', x: 250, y: 110, w: 100, h: 30 },
      { id: 'page', label: '담당자 호출', x: 40, y: 166, w: 130, h: 30 },
      { id: 'ch', label: '역할별 채널 5개', x: 190, y: 166, w: 150, h: 30 },
      { id: 'before', label: '흩어진 채널 17개', x: 190, y: 212, w: 150, h: 30 },
    ],
    edges: [
      { from: 'src', to: 'rules' },
      { from: 'rules', to: 's1' },
      { from: 'rules', to: 's2' },
      { from: 'rules', to: 's3' },
      { from: 's1', to: 'page' },
      { from: 's1', to: 'ch' },
      { from: 's2', to: 'ch' },
      { from: 's3', to: 'ch' },
    ],
    steps: [
      { caption: '지표와 로그를 모읍니다.', show: ['src'], active: ['src'] },
      { caption: '심각도별 규칙 36개로 판정합니다.', show: ['src', 'rules'], active: ['rules'] },
      { caption: '긴급 19, 높음 4, 통지 13으로 나눕니다.', show: ['src', 'rules', 's1', 's2', 's3'], active: ['s1', 's2', 's3'] },
      { caption: '긴급은 담당자 호출까지 이어집니다.', show: ['src', 'rules', 's1', 's2', 's3', 'page'], active: ['page'] },
      { caption: '모든 알림은 역할별 채널 5개로 모입니다. 전에는 17개였습니다.', show: ['src', 'rules', 's1', 's2', 's3', 'page', 'ch', 'before'], active: ['ch'], muted: ['before'] },
    ],
  },
  'restore-state-machine': {
    id: 'restore-state-machine',
    title: '첫 결제 혜택 자격 복원 흐름',
    width: 360,
    height: 236,
    nodes: [
      { id: 'tx', label: '주문 상태 변경', x: 10, y: 10, w: 170, h: 28 },
      { id: 'outbox', label: '아웃박스 기록', x: 10, y: 56, w: 170, h: 28 },
      { id: 'relay', label: 'Kafka로 전달', x: 10, y: 102, w: 170, h: 28 },
      { id: 'recheck', label: '조건 재확인, 잠금과 CAS', x: 10, y: 148, w: 170, h: 28 },
      { id: 'api', label: '결제 쪽 복원 API', x: 10, y: 194, w: 170, h: 28 },
      { id: 'w1', label: '대기', x: 210, y: 10, w: 140, h: 26 },
      { id: 'w2', label: '준비', x: 210, y: 50, w: 140, h: 26 },
      { id: 'w3', label: '예약', x: 210, y: 90, w: 140, h: 26 },
      { id: 'w4', label: '발송 중', x: 210, y: 130, w: 140, h: 26 },
      { id: 'w5', label: '확인', x: 210, y: 170, w: 140, h: 26 },
    ],
    edges: [
      { from: 'tx', to: 'outbox' },
      { from: 'outbox', to: 'relay' },
      { from: 'relay', to: 'recheck' },
      { from: 'recheck', to: 'api' },
      { from: 'w1', to: 'w2' },
      { from: 'w2', to: 'w3' },
      { from: 'w3', to: 'w4' },
      { from: 'w4', to: 'w5' },
    ],
    steps: [
      { caption: '판매자 잘못으로 첫 결제 주문이 모두 취소되면 상태가 바뀝니다.', show: ['tx'], active: ['tx'] },
      { caption: '같은 트랜잭션 안에서 아웃박스에 기록합니다. 작업은 대기 상태입니다.', show: ['tx', 'outbox', 'w1'], active: ['outbox', 'w1'] },
      { caption: 'Kafka로 전달되고 준비 상태가 됩니다.', show: ['tx', 'outbox', 'relay', 'w1', 'w2'], active: ['relay', 'w2'] },
      { caption: '보내기 직전에 조건을 다시 확인하고, 고객 단위 잠금과 CAS(값을 비교한 뒤 바꾸기)로 한 건만 진행합니다.', show: ['tx', 'outbox', 'relay', 'recheck', 'w1', 'w2', 'w3'], active: ['recheck', 'w3'] },
      { caption: '결제 쪽 API를 부르고 확인 상태로 저장합니다. 같은 요청은 중복 방지 키로 한 번만 처리합니다.', show: ['tx', 'outbox', 'relay', 'recheck', 'api', 'w1', 'w2', 'w3', 'w4', 'w5'], active: ['api', 'w5'] },
    ],
  },
};
